### ISSUE TITLE
Crash on callling the script a second time, on any window, index out of range

### ISSUE THREAD

**Issue by Araly** [jarvick257/rice#1]
I can *focus* an *unfocused* window, but I can't relaunch the script to get it back to normal, or launch the script a second time to focus another window. When launched from the terminal, I get an error when I call the script the second time, to try and *unfocus* a window.

```
Traceback (most recent call last):
  File ".config/i3/focus.py", line 52, in <module>
    main()
  File ".config/i3/focus.py", line 36, in main
    current = i3.filter(nodes=[], focused=True)[0]
IndexError: list index out of range
```

When I launch the script, I don't know if it's supposed to do that, and if it can help, but a title bar for a window appears in the background, with no attached window, where the now *focused* item was. When I mod+shift+a (azerty keyboard) to kill the focused window, I have to kill both now *focused* window and "remaining" of the window separately. I don't know if this is expected behavior, it might help with the issue, maybe.

![screenshot of issue and error](https://i.imgur.com/KczFdD4.png)

*focused* : as in with the focus.py script
focused : as in the window is focused, as a normal window would be in i3

Edit: So it appears that the crash only occurs when the phantom title bar is alive. When I kill it, (no need to kill the *focused* window) I can *focus* even more windows on top of the already *focused* one, each leaving a phantom title bar, that needs to be killed in order for the script not to crash. I assume the phantom title bar is here as a placeholder for the windows not to take over empty space as i3 windows would.

**Comment by jarvick257** [comment]
Ok first of, the window appearing in the background is expected behavior. I'm using this window as a placeholder to keep the tree structure unchanged when making a window floating. In my setup I disabled all window bars and didn't think about that this could happen. You can prevent this by adding `i3.border('none')` after creating that window in line 20.
Focusing more windows than one should never be possible. This might be connected to the error you're getting when your titlebar is running. For some reason the plugin doesn't find the active window. Can you maybe run a interactive python session in a terminal (probably just type `python3.6` and hit enter), then `import i3` and `i3.filter(nodes=[], focused=True)` and paste the output here?

**Comment by Araly** [comment]
I ran `python3.5` and `import i3`, `i3.filter(nodes=[], focused=True)` and here's the output : 
```
[{'scratchpad_state': 'none', 'window_rect': {'width': 940, 'height': 1015, 'y': 0, 'x': 0}, 'sticky': False, 'focus': [], 'deco_rect': {'width': 0, 'height': 0, 'y': 0, 'x': 0}, 'focused': True, 'current_border_width': 0, 'urgent': False, 'name': 'araly@araly-legion: ~', 'workspace_layout': 'default', 'percent': 0.5, 'layout': 'splith', 'geometry': {'width': 655, 'height': 386, 'y': 0, 'x': 0}, 'swallows': [], 'floating_nodes': [], 'output': 'eDP-1', 'last_split_layout': 'splith', 'fullscreen_mode': 0, 'type': 'con', 'orientation': 'none', 'floating': 'auto_off', 'window': 44040244, 'window_properties': {'instance': 'gnome-terminal-server', 'title': 'araly@araly-legion: ~', 'transient_for': None, 'class': 'Gnome-terminal', 'window_role': 'gnome-terminal-window-851fcdf1-8a59-4227-b23d-082ac56632b8'}, 'border': 'pixel', 'id': 36678544, 'rect': {'width': 940, 'height': 1015, 'y': 50, 'x': 965}, 'nodes': []}]
```

I can focus more windows when I kill the phantom window titlebar placeholder. I think as long as this window still exist, the script tries to unfocus the focused window, which crashes. When I kill the phantom window, I can focus something else, on top of the already focused window.

**Comment by jarvick257** [comment]
That output looks correct. That was from an unfocused window, right? Can you do the same in a focused window? And if that's [], send me the output for 'i3.filter(nodes=[])'.
Did you manage to hide the title bar of the placeholder window?

**Comment by Araly** [comment]
Okay, I haven't fully understood, so yeah, previous output was an unfocused terminal window, with no focused windows around. The output for `i3.filter(nodes=[], focused=True)` is indeed just `[]`. Here is the output for `i3.filter(nodes=[])`, with only one terminal and no other windows open at all, first unfocused, then focused : 

```
[{'layout': 'splith', 'current_border_width': -1, 'orientation': 'none', 'swallows': [], 'sticky': False, 'workspace_layout': 'default', 'output': '__i3', 'id': 28837584, 'last_split_layout': 'splith', 'focus': [], 'nodes': [], 'window_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'geometry': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'floating_nodes': [], 'gaps': {'inner': 0, 'outer': 0}, 'floating': 'auto_off', 'name': '__i3_scratch', 'num': -1, 'border': 'normal', 'urgent': False, 'fullscreen_mode': 1, 'focused': False, 'rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'type': 'workspace', 'deco_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'window': None, 'percent': None, 'scratchpad_state': 'none'}, {'layout': 'splith', 'current_border_width': 2, 'orientation': 'none', 'swallows': [], 'sticky': True, 'workspace_layout': 'default', 'output': 'eDP-1', 'id': 28880064, 'last_split_layout': 'splith', 'focus': [], 'window_rect': {'height': 35, 'x': 0, 'width': 1920, 'y': 0}, 'geometry': {'height': 35, 'x': 0, 'width': 1920, 'y': 0}, 'floating_nodes': [], 'floating': 'auto_off', 'name': 'polybar-example_eDP-1', 'nodes': [], 'window_properties': {'instance': 'polybar', 'title': 'polybar-example_eDP-1', 'transient_for': None, 'class': 'Polybar'}, 'border': 'normal', 'urgent': False, 'fullscreen_mode': 0, 'focused': False, 'rect': {'height': 35, 'x': 0, 'width': 1920, 'y': 0}, 'type': 'con', 'deco_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'window': 6291458, 'percent': 1.0, 'scratchpad_state': 'none'}, {'layout': 'splith', 'current_border_width': 0, 'orientation': 'none', 'swallows': [], 'sticky': False, 'workspace_layout': 'default', 'output': 'eDP-1', 'id': 28878608, 'last_split_layout': 'splith', 'focus': [], 'window_rect': {'height': 1015, 'x': 0, 'width': 1890, 'y': 0}, 'geometry': {'height': 386, 'x': 0, 'width': 655, 'y': 0}, 'floating_nodes': [], 'floating': 'auto_off', 'name': 'araly@araly-legion: ~', 'nodes': [], 'window_properties': {'instance': 'gnome-terminal-server', 'title': 'araly@araly-legion: ~', 'window_role': 'gnome-terminal-window-3ea07854-98ed-4040-822e-0733ef366da9', 'transient_for': None, 'class': 'Gnome-terminal'}, 'border': 'pixel', 'urgent': False, 'fullscreen_mode': 0, 'focused': True, 'rect': {'height': 1015, 'x': 15, 'width': 1890, 'y': 50}, 'type': 'con', 'deco_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'window': 31457286, 'percent': 1.0, 'scratchpad_state': 'none'}, {'layout': 'dockarea', 'current_border_width': -1, 'orientation': 'none', 'swallows': [{'insert_where': 2, 'dock': 3}], 'sticky': False, 'workspace_layout': 'default', 'output': 'eDP-1', 'id': 28851248, 'last_split_layout': 'splith', 'focus': [], 'window_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'geometry': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'floating_nodes': [], 'floating': 'auto_off', 'name': 'bottomdock', 'nodes': [], 'border': 'normal', 'urgent': False, 'fullscreen_mode': 0, 'focused': False, 'rect': {'height': 0, 'x': 0, 'width': 1920, 'y': 1080}, 'type': 'dockarea', 'deco_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'window': None, 'percent': None, 'scratchpad_state': 'none'}]

```

```
[{'layout': 'splith', 'current_border_width': -1, 'orientation': 'none', 'swallows': [], 'sticky': False, 'workspace_layout': 'default', 'output': '__i3', 'id': 28837584, 'last_split_layout': 'splith', 'focus': [], 'nodes': [], 'window_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'geometry': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'floating_nodes': [], 'gaps': {'inner': 0, 'outer': 0}, 'floating': 'auto_off', 'name': '__i3_scratch', 'num': -1, 'border': 'normal', 'urgent': False, 'fullscreen_mode': 1, 'focused': False, 'rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'type': 'workspace', 'deco_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'window': None, 'percent': None, 'scratchpad_state': 'none'}, {'layout': 'splith', 'current_border_width': 2, 'orientation': 'none', 'swallows': [], 'sticky': True, 'workspace_layout': 'default', 'output': 'eDP-1', 'id': 28880064, 'last_split_layout': 'splith', 'focus': [], 'window_rect': {'height': 35, 'x': 0, 'width': 1920, 'y': 0}, 'geometry': {'height': 35, 'x': 0, 'width': 1920, 'y': 0}, 'floating_nodes': [], 'floating': 'auto_off', 'name': 'polybar-example_eDP-1', 'nodes': [], 'window_properties': {'instance': 'polybar', 'title': 'polybar-example_eDP-1', 'transient_for': None, 'class': 'Polybar'}, 'border': 'normal', 'urgent': False, 'fullscreen_mode': 0, 'focused': False, 'rect': {'height': 35, 'x': 0, 'width': 1920, 'y': 0}, 'type': 'con', 'deco_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'window': 6291458, 'percent': 1.0, 'scratchpad_state': 'none'}, {'layout': 'splith', 'current_border_width': -1, 'orientation': 'none', 'swallows': [], 'sticky': False, 'workspace_layout': 'default', 'output': 'eDP-1', 'id': 28349984, 'last_split_layout': 'splith', 'focus': [], 'window_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'geometry': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'floating_nodes': [], 'floating': 'auto_off', 'name': None, 'nodes': [], 'border': 'normal', 'urgent': False, 'fullscreen_mode': 0, 'focused': False, 'rect': {'height': 995, 'x': 15, 'width': 1890, 'y': 70}, 'type': 'con', 'deco_rect': {'height': 20, 'x': 15, 'width': 1890, 'y': 15}, 'window': None, 'percent': 1.0, 'scratchpad_state': 'none'}, {'layout': 'dockarea', 'current_border_width': -1, 'orientation': 'none', 'swallows': [{'insert_where': 2, 'dock': 3}], 'sticky': False, 'workspace_layout': 'default', 'output': 'eDP-1', 'id': 28851248, 'last_split_layout': 'splith', 'focus': [], 'window_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'geometry': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'floating_nodes': [], 'floating': 'auto_off', 'name': 'bottomdock', 'nodes': [], 'border': 'normal', 'urgent': False, 'fullscreen_mode': 0, 'focused': False, 'rect': {'height': 0, 'x': 0, 'width': 1920, 'y': 1080}, 'type': 'dockarea', 'deco_rect': {'height': 0, 'x': 0, 'width': 0, 'y': 0}, 'window': None, 'percent': None, 'scratchpad_state': 'none'}]

```

I'm pretty sure it's exactly the same output. As far as I understand, the script seems to rely on a "focused" variable, to know which window is focused, but python can't find it ? So when you try to access the first element of what should be the output of `i3.filter(nodes=[], focused=True)`, it throws a index out of range error, as the first element doesn't exist. "focused" is an i3 thing apparently, as I don't see the script declaring it, but somehow it messes it up. 

I haven't tried hiding the placeholder window, it doesn't bother me much. Do you want me to try it anyways ?

**Comment by jarvick257** [comment]
Yeah you pretty much got it right. The filter function just filters parts from the full i3 window tree. `focused` is one attribute there that should be `True` for the currently active window. `nodes=[]` just makes sure that you are getting the window object and not the container or workspace.
But this is getting weird... the output clearly says that for the terminal window `focused: True` but the filter function doesn't recognize that. It's either a problem with the plugin for your distribution or i3 itself. I've also noticed that the windows do not have an 'id'. For comparison, that's what you should see for `i3.filter(nodes=[], focused=True)`:
```
[{'id': 94337723310256, 'type': 'con', 'orientation': 'none', 'scratchpad_state': 'none', 'percent': 0.5, 'urgent': False, 'focused': True, 'output': 'HDMI-0', 'layout': 'splith', 'workspace_layout': 'default', 'last_split_layout': 'splith', 'border': 'none', 'current_border_width': 0, 'rect': {'x': 982, 'y': 576, 'width': 869, 'height': 435}, 'deco_rect': {'x': 0, 'y': 0, 'width': 0, 'height': 0}, 'window_rect': {'x': 0, 'y': 0, 'width': 869, 'height': 435}, 'geometry': {'x': 2262, 'y': 562, 'width': 869, 'height': 449}, 'name': 'python3', 'window': 16777219, 'window_properties': {'class': 'Termite', 'instance': 'termite', 'title': 'python3', 'transient_for': None}, 'nodes': [], 'floating_nodes': [], 'focus': [], 'fullscreen_mode': 0, 'sticky': False, 'floating': 'auto_off', 'swallows': []}]
```
What you can try to avoid `i3.filter` is parsing the i3 tree yourself. I uploaded a 'focus_noFilter.py' script. See if that works better.

**Comment by Araly** [comment]
I tried with focus_noFilter.py, but it doesn't work, it doesn't focus or unfocus. here is the output when called from the terminal : 
```
Traceback (most recent call last):
  File ".config/i3/focus_noFilter.py", line 65, in <module>
    main()
  File ".config/i3/focus_noFilter.py", line 48, in main
    root = json.loads(tree)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```

**Comment by jarvick257** [comment]
Are you using i3 or i3-gaps?
What does `i3 --version` output?
And post the output of `i3-msg -t get_tree`

**Comment by ghost** [comment]
If you need a third troubleshooter, im happy to help, really love the idea of this script. Am using i3-gaps. I also have the same issue as @Araly

**Comment by jarvick257** [comment]
ehm sure. If you happen to have the same results so far, I don't see why not. At this point i'm guessing that you're using a different i3 version which the script doesn't work for. But I need the results of my last post for that

**Comment by ghost** [comment]
`i3 --version` =  `i3 version 4.14.1-200-gcbaf923 (2017-11-29, branch "gaps-next") © 2009 Michael Stapelberg and contributors`
[get_tree output](https://iv-l.xyz/ftp/get_tree)

**Comment by jarvick257** [comment]
That also looks correct.
I added a line to the script, converting the output from byte to string. Wasn't necessary on my machine but maybe that's because you're using python 3.5 and not 3.6? No idea...
Try the new version

**Comment by ghost** [comment]
The windows now float and go back to normal state, but the position and dimension of the floated windows are random. This is using python3.5

**Comment by jarvick257** [comment]
Try opening a python session and type in the following commands and see if the window behaves as expected:
```python
import i3
i3.floating('enable')
i3.resize('set 1000 1000')
i3.move('position center')
```
if not, try the following commands in a regular terminal (not python)
```bash
i3-msg floating enable
i3-msg resize set 1000 1000
i3-msg move position center
```

**Comment by ghost** [comment]
Both approaches worked as expected.

**Comment by jarvick257** [comment]
That doesn't make any sense. The window becomes floating, so `make_float()` starts, focuses the right window, makes it floating but then just doesn't execute the following two commands?
Or did you mean the position and size of the window are random when you unfocus it?

**Comment by Araly** [comment]
I have the new version of focus_noFilter.py and everything works. The window gets focused, and returns to normal state. 

i3 --version : `i3 version 4.14.1-168-g5533e52 (2017-10-25, branch "gaps-next") © 2009 Michael Stapelberg and contributors`

Running i3-msg -t get-tree doesn't work and outputs : 
```
Unknown message type
Known types: run_command, get_workspaces, get_outputs, get_tree, get_marks, get_bar_config, get_binding_modes, get_version, get_config, send_tick
```

**Comment by ghost** [comment]
Nevermind, tried it again now and it works perfectly. Thanks alot. @Araly seems like a typo it should be `i3-msg -t get_tree`

**Comment by jarvick257** [comment]
Nice! Finally :D

**Comment by Araly** [comment]
Okay, it was a typo, it outputs a huge wall of text.

Well thanks a lot for spending all that time to get your script to work. I'll be sure to recommend when I can.
